//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPROSanXuat_Checklist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist
    {
        public Checklist()
        {
            this.Checklist_JobStep = new HashSet<Checklist_JobStep>();
        }
    
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PODetailId { get; set; }
        public int ObjectType { get; set; }
        public string Name { get; set; }
        public double ProductionDays { get; set; }
        public int Quantities { get; set; }
        public double Productivity { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RealEndDate { get; set; }
        public string RelatedEmployees { get; set; }
        public int StatusId { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<Checklist_JobStep> Checklist_JobStep { get; set; }
        public virtual PO_SellDetail PO_SellDetail { get; set; }
        public virtual Template_Checklist Template_Checklist { get; set; }
    }
}
