//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPROSanXuat_Checklist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist_Job
    {
        public Checklist_Job()
        {
            this.Checklist_Job_ActionLog = new HashSet<Checklist_Job_ActionLog>();
            this.Checklist_Job_Alert = new HashSet<Checklist_Job_Alert>();
            this.Checklist_Job_Attachment = new HashSet<Checklist_Job_Attachment>();
            this.Checklist_Job_Comment = new HashSet<Checklist_Job_Comment>();
            this.Checklist_Job_EmployeeReference = new HashSet<Checklist_Job_EmployeeReference>();
            this.Checklist_Job_Error = new HashSet<Checklist_Job_Error>();
            this.Checklist_Job_NotifyLog = new HashSet<Checklist_Job_NotifyLog>();
        }
    
        public int Id { get; set; }
        public int FakeId { get; set; }
        public int ChecklistJobStepId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int JobIndex { get; set; }
        public string Name { get; set; }
        public string JobContent { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string RelatedEmployees { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RealEndDate { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public double Quantities { get; set; }
        public double RealQuantities { get; set; }
        public int StatusId { get; set; }
        public bool HasViewProductivity { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<Checklist_Job_ActionLog> Checklist_Job_ActionLog { get; set; }
        public virtual ICollection<Checklist_Job_Alert> Checklist_Job_Alert { get; set; }
        public virtual ICollection<Checklist_Job_Attachment> Checklist_Job_Attachment { get; set; }
        public virtual Checklist_JobStep Checklist_JobStep { get; set; }
        public virtual ICollection<Checklist_Job_Comment> Checklist_Job_Comment { get; set; }
        public virtual ICollection<Checklist_Job_EmployeeReference> Checklist_Job_EmployeeReference { get; set; }
        public virtual ICollection<Checklist_Job_Error> Checklist_Job_Error { get; set; }
        public virtual ICollection<Checklist_Job_NotifyLog> Checklist_Job_NotifyLog { get; set; }
    }
}
