//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPROSanXuat_Checklist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public Delivery()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetail>();
        }
    
        public int Id { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public int WarehouseId { get; set; }
        public int CustomerId { get; set; }
        public string Reciever { get; set; }
        public int UnitId { get; set; }
        public double ExchangeRate { get; set; }
        public int TransactionType { get; set; }
        public System.DateTime DateOfAccounting { get; set; }
        public string Note { get; set; }
        public Nullable<int> ApprovedUser { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int Deliverier { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUser { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<DeliveryDetail> DeliveryDetails { get; set; }
    }
}
