//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPROSanXuat_Checklist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Sell
    {
        public PO_Sell()
        {
            this.Orders = new HashSet<Order>();
            this.PO_SellDetail = new HashSet<PO_SellDetail>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int CustomerId { get; set; }
        public string Phone { get; set; }
        public string Note { get; set; }
        public int MoneyUnitId { get; set; }
        public double Exchange { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PO_SellDetail> PO_SellDetail { get; set; }
    }
}
