//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPROSanXuat_Checklist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionFile
    {
        public ProductionFile()
        {
            this.ProFileControls = new HashSet<ProFileControl>();
        }
    
        public int Id { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public int TemplateFileId { get; set; }
        public string Content { get; set; }
        public string CodeUrl { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> ApprovedUser { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedUser { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual TemplateFile TemplateFile { get; set; }
        public virtual ICollection<ProFileControl> ProFileControls { get; set; }
    }
}
