//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPROSanXuat_Checklist.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_CL_JobStep
    {
        public Template_CL_JobStep()
        {
            this.Template_CL_Job = new HashSet<Template_CL_Job>();
        }
    
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public int StepIndex { get; set; }
        public string Name { get; set; }
        public string JobStepContent { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Template_Checklist Template_Checklist { get; set; }
        public virtual ICollection<Template_CL_Job> Template_CL_Job { get; set; }
    }
}
